# Generated by Django 3.1.2 on 2020-11-06 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('potato', models.IntegerField(default=10)),
                ('bean', models.IntegerField(default=5)),
            ],
        ),
    ]
