# Generated by Django 3.1.2 on 2020-10-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('item', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=99)),
            ],
        ),
    ]
