# Generated by Django 3.1.2 on 2020-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='day',
            field=models.CharField(default='Friday', max_length=200),
        ),
    ]
