# Generated by Django 3.1.2 on 2020-10-29 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacoapp', '0002_food_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
