# Generated by Django 3.1.2 on 2020-11-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tacoapp', '0002_food_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day',
        ),
    ]
