# Generated by Django 3.1.2 on 2020-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacoapp', '0003_remove_food_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='weekday',
            field=models.CharField(default='Monday', max_length=200),
        ),
    ]
